apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - image: 058264539722.dkr.ecr.us-east-2.amazonaws.com/notifications:latest
          name: notifications
          env:
            - name: TCP_PORT
              valueFrom:
                secretKeyRef:
                  name: ntcpport
                  key: ntcpPort
            - name: MAILTRAP_USER
              valueFrom:
                secretKeyRef:
                  name: mailtrapuser
                  key: mailtrapUser
            - name: MAILTRAP_PASS
              valueFrom:
                secretKeyRef:
                  name: mailtrappass
                  key: mailtrapPass
            - name: MAILTRAP_HOST
              valueFrom:
                secretKeyRef:
                  name: mailtraphost
                  key: mailtrapHost
            - name: MAILTRAP_PORT
              valueFrom:
                secretKeyRef:
                  name: mailtrapport
                  key: mailtrapPort
          ports:
            - containerPort: 3004
